// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.Repository.PmsDbContext;

#nullable disable

namespace PMS.WebAPI.Migrations
{
    [DbContext(typeof(PmsDbContext))]
    [Migration("20260504155756_Seeding data")]
    partial class Seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMS.Repository.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 100001,
                            CreationDate = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4171),
                            Description = "Test product for demonstration",
                            LastUpdated = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4172),
                            Name = "Sample Product",
                            Price = 10.0,
                            Stock = 100
                        },
                        new
                        {
                            Id = 100002,
                            CreationDate = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4173),
                            Description = "High-end laptop for professionals",
                            LastUpdated = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4174),
                            Name = "Laptop Pro",
                            Price = 1500.0,
                            Stock = 50
                        },
                        new
                        {
                            Id = 100003,
                            CreationDate = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4175),
                            Description = "Ergonomic wireless mouse",
                            LastUpdated = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4175),
                            Name = "Wireless Mouse",
                            Price = 50.0,
                            Stock = 200
                        },
                        new
                        {
                            Id = 100004,
                            CreationDate = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4177),
                            Description = "Comfortable office chair",
                            LastUpdated = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4177),
                            Name = "Office Chair",
                            Price = 150.0,
                            Stock = 100
                        },
                        new
                        {
                            Id = 100005,
                            CreationDate = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4178),
                            Description = "Latest smartphone with advanced features",
                            LastUpdated = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4178),
                            Name = "Smartphone X",
                            Price = 999.0,
                            Stock = 75
                        },
                        new
                        {
                            Id = 100006,
                            CreationDate = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4179),
                            Description = "Next-gen gaming console",
                            LastUpdated = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4180),
                            Name = "Gaming Console",
                            Price = 499.0,
                            Stock = 30
                        },
                        new
                        {
                            Id = 100007,
                            CreationDate = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4181),
                            Description = "Portable Bluetooth speaker with high-quality sound",
                            LastUpdated = new DateTime(2026, 5, 4, 15, 57, 56, 97, DateTimeKind.Utc).AddTicks(4181),
                            Name = "Bluetooth Speaker",
                            Price = 120.0,
                            Stock = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
